application: deutsche-bahn-api
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
   - url: /api-docs
     static_files: swagger.json
     upload: swagger.json

   - url: /docs
     static_files: vendor/swagger-api/swagger-ui/dist/index.html
     upload: vendor/swagger-api/swagger-ui/dist/index.html

   - url: /docs/(.*)
     static_files: vendor/swagger-api/swagger-ui/dist/\1
     upload: vendor/swagger-api/swagger-ui/dist/.

   - url: /static
     static_dir: static
     application_readable: true
     secure: always

   - url: .*
     script: api.php